# Generated by Django 4.2.4 on 2023-10-10 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rol_user_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='rol_nombre',
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
