# Generated by Django 4.2.4 on 2023-10-10 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_rol_rol_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propuesta',
            name='pro_estado',
            field=models.CharField(blank=True, choices=[('ACTIVO', 'ACTIVO'), ('INACTIVO', 'INACTIVO')], default='ACTIVO', max_length=45),
        ),
    ]
