# Generated by Django 4.2.4 on 2023-10-10 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_propuesta_pro_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propuesta',
            name='pro_estado',
            field=models.CharField(blank=True, default='ACTIVO', max_length=45),
        ),
    ]
