# Generated by Django 4.2.4 on 2023-10-10 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_propuesta_pro_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='rol_estado',
            field=models.CharField(blank=True, choices=[('ACTIVO', 'ACTIVO'), ('INACTIVO', 'INACTIVO')], default='ACTIVO', max_length=45),
        ),
    ]
