# Generated by Django 4.2.4 on 2023-10-11 06:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_rol_rol_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnteProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antp_titulo', models.CharField(max_length=255)),
                ('antp_descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_nombre', models.CharField(max_length=45)),
                ('doc_ruta', models.FileField(blank=True, upload_to='documentos_user')),
                ('anteproyectos', models.ManyToManyField(blank=True, related_name='antp_soporte_doc', to='api.anteproyecto')),
            ],
        ),
        migrations.CreateModel(
            name='TrabajoDeGrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trag_titulo', models.CharField(max_length=255)),
                ('trag_modalidad', models.CharField(max_length=45)),
                ('trag_fecha_recepcion', models.DateField()),
                ('trag_fecha_sustentacion', models.DateField()),
                ('trag_estado', models.CharField(blank=True, max_length=45)),
                ('documentos', models.ManyToManyField(blank=True, related_name='trag_soporte_doc', to='api.documento')),
                ('usuarios', models.ManyToManyField(blank=True, related_name='user_realiza_trag', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seg_observaciones', models.TextField()),
                ('seg_fecha_recepcion', models.DateField()),
                ('seg_fecha_asignacion', models.DateField()),
                ('seg_fecha_concepto', models.DateField()),
                ('seg_estado', models.CharField(blank=True, max_length=45)),
                ('anteproyectos', models.ManyToManyField(blank=True, related_name='antp_seguido_seg', to='api.anteproyecto')),
                ('usuarios', models.ManyToManyField(blank=True, related_name='user_sigue_seg', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='documento',
            name='trabajos_de_grado',
            field=models.ManyToManyField(blank=True, related_name='trag_soporte_doc', to='api.trabajodegrado'),
        ),
        migrations.AddField(
            model_name='anteproyecto',
            name='documentos',
            field=models.ManyToManyField(blank=True, related_name='antp_soporte_doc', to='api.documento'),
        ),
        migrations.AddField(
            model_name='anteproyecto',
            name='seguimientos',
            field=models.ManyToManyField(blank=True, related_name='antp_seguido_seg', to='api.seguimiento'),
        ),
        migrations.AddField(
            model_name='anteproyecto',
            name='usuarios',
            field=models.ManyToManyField(blank=True, related_name='user_participa_antp', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='anteproyectos',
            field=models.ManyToManyField(blank=True, related_name='user_participa_antp', to='api.anteproyecto'),
        ),
        migrations.AddField(
            model_name='user',
            name='seguimientos',
            field=models.ManyToManyField(blank=True, related_name='user_sigue_seg', to='api.seguimiento'),
        ),
        migrations.AddField(
            model_name='user',
            name='trabajos_de_grado',
            field=models.ManyToManyField(blank=True, related_name='user_realiza_trag', to='api.trabajodegrado'),
        ),
    ]
