# Generated by Django 4.2.4 on 2023-10-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_anteproyecto_documento_trabajodegrado_seguimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimiento',
            name='seg_observaciones',
            field=models.TextField(blank=True),
        ),
    ]
