# Generated by Django 4.2.4 on 2023-10-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_seguimiento_seg_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimiento',
            name='seg_fecha_asignacion',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='seg_fecha_concepto',
            field=models.DateField(blank=True),
        ),
    ]
