# Generated by Django 4.2.4 on 2023-10-11 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_seguimiento_seg_fecha_asignacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimiento',
            name='seg_fecha_asignacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='seg_fecha_concepto',
            field=models.DateField(blank=True, null=True),
        ),
    ]
