# Generated by Django 4.2.4 on 2023-10-12 00:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_seguimiento_seg_fecha_asignacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AntpSeguidoSeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AntpSoporteDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TrabajoGrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trag_titulo', models.CharField(max_length=255)),
                ('trag_modalidad', models.CharField(max_length=45)),
                ('trag_fecha_recepcion', models.DateField()),
                ('trag_fecha_sustentacion', models.DateField()),
                ('trag_estado', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='TragSoporteDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserParticipaAntp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserRealizaTrag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.trabajogrado')),
            ],
        ),
        migrations.CreateModel(
            name='UserSigueSeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='anteproyecto',
            name='documentos',
        ),
        migrations.RemoveField(
            model_name='anteproyecto',
            name='seguimientos',
        ),
        migrations.RemoveField(
            model_name='anteproyecto',
            name='usuarios',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='anteproyectos',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='trabajos_de_grado',
        ),
        migrations.RemoveField(
            model_name='seguimiento',
            name='anteproyectos',
        ),
        migrations.RemoveField(
            model_name='seguimiento',
            name='usuarios',
        ),
        migrations.RemoveField(
            model_name='user',
            name='anteproyectos',
        ),
        migrations.RemoveField(
            model_name='user',
            name='seguimientos',
        ),
        migrations.RemoveField(
            model_name='user',
            name='trabajos_de_grado',
        ),
        migrations.AlterField(
            model_name='documento',
            name='doc_nombre',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='documento',
            name='doc_ruta',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='seg_estado',
            field=models.CharField(max_length=45),
        ),
        migrations.DeleteModel(
            name='TrabajoDeGrado',
        ),
        migrations.AddField(
            model_name='usersigueseg',
            name='seg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.seguimiento'),
        ),
        migrations.AddField(
            model_name='usersigueseg',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userrealizatrag',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userparticipaantp',
            name='antp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.anteproyecto'),
        ),
        migrations.AddField(
            model_name='userparticipaantp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tragsoportedoc',
            name='doc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.documento'),
        ),
        migrations.AddField(
            model_name='tragsoportedoc',
            name='trag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.trabajogrado'),
        ),
        migrations.AddField(
            model_name='antpsoportedoc',
            name='antp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.anteproyecto'),
        ),
        migrations.AddField(
            model_name='antpsoportedoc',
            name='doc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.documento'),
        ),
        migrations.AddField(
            model_name='antpseguidoseg',
            name='antp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.anteproyecto'),
        ),
        migrations.AddField(
            model_name='antpseguidoseg',
            name='seg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.seguimiento'),
        ),
    ]
