# Generated by Django 4.2.4 on 2023-11-09 22:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_userrealizatrag_trag_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anteproyecto',
            name='evaluadores',
            field=models.ManyToManyField(related_name='anteproyectos_evaluados', to=settings.AUTH_USER_MODEL),
        ),
    ]
