# Generated by Django 4.2.4 on 2023-11-13 21:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_trabajogrado_trag_modalidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anteproyecto',
            name='evaluadores',
            field=models.ManyToManyField(blank=True, null=True, related_name='anteproyectos_evaluados', to=settings.AUTH_USER_MODEL),
        ),
    ]
