# Generated by Django 4.2.4 on 2023-11-21 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_anteproyecto_evaluadores'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimiento',
            name='docs',
            field=models.ManyToManyField(blank=True, related_name='seguimientos', to='api.documento'),
        ),
    ]
