# Generated by Django 4.2.4 on 2023-11-21 20:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_seguimiento_docs'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajogrado',
            name='jurados',
            field=models.ManyToManyField(blank=True, related_name='trabajos_grado_jurados', to=settings.AUTH_USER_MODEL),
        ),
    ]
