# Generated by Django 4.2.4 on 2023-11-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_documento_doc_fecha_creacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trabajogrado',
            old_name='trag_fecha_recepcion',
            new_name='trag_fecha_inicio',
        ),
        migrations.AddField(
            model_name='trabajogrado',
            name='trag_fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
