# Generated by Django 4.2.4 on 2023-11-28 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_anteproyecto_docs_historial_anteproyecto_pro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anteproyecto',
            name='docs_historial',
            field=models.ManyToManyField(blank=True, null=True, related_name='anteproyectos_documentosh', to='api.documento'),
        ),
        migrations.AlterField(
            model_name='anteproyecto',
            name='pro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anteproyectos_propuesta', to='api.propuesta'),
        ),
    ]
