# Generated by Django 4.2.4 on 2023-11-29 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_anteproyecto_docs_historial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propuesta',
            name='doc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='propuestas_documentos', to='api.documento'),
            preserve_default=False,
        ),
    ]
