# Generated by Django 4.2.4 on 2023-11-29 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_remove_propuesta_pro_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propuesta',
            name='pro_estado',
            field=models.CharField(blank=True, choices=[('PENDIENTE', 'PENDIENTE'), ('APROBADO', 'APROBADO'), ('RECHAZADO', 'RECHAZADO')], default='PENDIENTE', max_length=45),
        ),
    ]
