# Generated by Django 4.2.4 on 2023-11-29 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_documento_doc_fecha_creacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anteproyecto',
            old_name='pro',
            new_name='propuesta',
        ),
    ]
