# Generated by Django 4.2.4 on 2023-11-29 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_rename_pro_anteproyecto_propuesta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anteproyecto',
            name='antp_modalidad',
        ),
        migrations.AddField(
            model_name='propuesta',
            name='pro_modalidad',
            field=models.CharField(blank=True, choices=[('Trabajo de Investigación', 'Trabajo de Investigación'), ('Práctica Profesional', 'Práctica Profesional')], default='Trabajo de Investigación', max_length=45),
        ),
    ]
