# Generated by Django 4.2.4 on 2023-11-30 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_remove_anteproyecto_antp_modalidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anteproyecto',
            name='propuesta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anteproyectos_propuesta', to='api.propuesta'),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='seg_estado',
            field=models.CharField(blank=True, default='PENDIENTE', max_length=45),
        ),
    ]
