# Generated by Django 4.2.6 on 2023-11-30 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_alter_anteproyecto_propuesta_and_more'),
        ('api', '0036_alter_seguimiento_seg_estado'),
    ]

    operations = [
    ]
