# Generated by Django 4.2.6 on 2023-11-30 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_merge_20231129_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimiento',
            name='seg_estado',
            field=models.CharField(blank=True, choices=[('PENDIENTE', 'PENDIENTE'), ('A revisión', 'A revisión'), ('No Aprobado', 'No Aprobado'), ('Evaluado', 'Evaluado'), ('Remitido', 'Remitido')], default='PENDIENTE', max_length=45),
        ),
    ]
