# Generated by Django 4.2.6 on 2023-11-30 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_alter_seguimiento_seg_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimiento',
            name='seg_estado',
            field=models.CharField(blank=True, choices=[('PENDIENTE', 'PENDIENTE'), ('A revisión', 'A revisión'), ('No Aprobado', 'No Aprobado'), ('Aprobado', 'Aprobado'), ('Evaluado', 'Evaluado'), ('Remitido', 'Remitido')], default='PENDIENTE', max_length=45),
        ),
    ]
