# Generated by Django 4.2.6 on 2023-11-30 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_alter_seguimiento_seg_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajogrado',
            name='trag_estado',
            field=models.CharField(blank=True, default='PENDIENTE', max_length=45),
        ),
    ]
