# Generated by Django 4.2.4 on 2023-12-02 21:17

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_alter_trabajogrado_trag_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='propuesta',
            name='pro_fecha_creacion',
            field=models.DateField(default=api.models.Propuesta.default_fecha_creacion),
        ),
        migrations.AddField(
            model_name='propuesta',
            name='pro_fecha_max',
            field=models.DateField(default=api.models.Propuesta.default_fecha_max),
        ),
        migrations.AddField(
            model_name='trabajogrado',
            name='trag_fecha_sustentacion_max',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trabajogrado',
            name='trag_fecha_sustentacion_min',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propuesta',
            name='pro_estado',
            field=models.CharField(blank=True, choices=[('PENDIENTE', 'PENDIENTE'), ('PLAZO VENCIDO', 'PLAZO VENCIDO'), ('APROBADO', 'APROBADO'), ('RECHAZADO', 'RECHAZADO')], default='PENDIENTE', max_length=45),
        ),
    ]
