# Generated by Django 4.2.4 on 2023-12-03 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_propuesta_pro_fecha_creacion_propuesta_pro_fecha_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(blank=True, default='default.png', upload_to='user_images'),
        ),
    ]
