# Generated by Django 4.2.4 on 2023-12-04 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_alter_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajogrado',
            name='trag_estado',
            field=models.CharField(blank=True, choices=[('ACTIVO', 'ACTIVO'), ('PENDIENTE', 'PENDIENTE'), ('PRÓRROGA SOLICITADA', 'PRÓRROGA SOLICITADA'), ('PRÓRROGA APROBADA', 'PRÓRROGA APROBADA'), ('PRÓRROGA NO APROBADA', 'PRÓRROGA NO APROBADA'), ('APROBADO', 'APROBADO'), ('APROBADO CON OBSERVACIONES', 'APROBADO CON OBSERVACIONES'), ('APLAZADO', 'APLAZADO'), ('NO APROBADO', 'NO APROBADO'), ('CANCELADO', 'CANCELADO')], default='PENDIENTE', max_length=45),
        ),
    ]
