# Generated by Django 4.2.4 on 2023-12-04 21:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_trabajogrado_trag_numero_sustentacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialEstadoTrag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trag_estado', models.CharField(max_length=45)),
                ('fecha_cambio', models.DateTimeField(default=django.utils.timezone.now)),
                ('trag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='api.trabajogrado')),
            ],
            options={
                'ordering': ['-fecha_cambio'],
            },
        ),
    ]
