# Generated by Django 4.2.4 on 2023-12-04 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_alter_trabajogrado_trag_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajogrado',
            name='trag_fecha_sustentacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
