# Generated by Django 4.2.4 on 2023-12-04 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_alter_trabajogrado_trag_fecha_sustentacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajogrado',
            name='trag_numero_sustentacion',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
